name: Python Application

on: 
  push:

jobs:
  build:
    run-on: ubuntu-latest
    steps:
  - name: Clone Repo to Runner
    uses: actions/checkout@v3
  - name: Set up Python Version
    uses: actions/setup-python@v3
    with:
      python-version: "3.10"
  - name: Install Dependencies
    run: pip3 install -r requirements.txt
  - name: Automated Unit Testing
    run: python test.py